[build]
target = "thumbv7em-none-eabihf"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F407ZGTx --no-location"

[target.thumbv7em-none-eabihf]
rustflags = [
  "-C", "linker=flip-link",
]

[env]
DEFMT_LOG = "trace"
