[package]
name = "wire-protocols"
version = "0.1.0"
edition = "2021"
authors = ["Jon Lamb"]

[dependencies]
defmt = "0.3"

[dependencies.bitfield]
version = "0.14"
default-features = false

[dependencies.byteorder]
version = "1"
default-features = false
